akka {
  loglevel = "INFO"
  stdout-loglevel = "INFO"
  loggers = ["akka.event.slf4j.Slf4jLogger"]
}

kafka {
  bootstrap-servers = "localhost:9092"
  group-id = "event-management"
  topic = "event-notifications"
  poll-interval-ms = 500
  auto-offset-reset = "latest"
}
email {
  mode = "smtp"
  from = "equipment.event.services@gmail.com"

  smtp {
    host = "smtp.gmail.com"
    port = 587
    user = "equipment.event.services@gmail.com"
    pass = "atst bylm rrqn ahrn"
  }
}



