# https://www.playframework.com/documentation/latest/Configuration
# https://www.playframework.com/documentation/latest/Configuration
play.server.http.address = "0.0.0.0"
# Optional: Set the port if you want something other than the default (9000)
play.server.http.port = 9000
#play.http.filters = "filters.Filters"
play.filters.enabled += "play.filters.cors.CORSFilter"
play.modules.enabled+="modules.Module"

# Enable Play's default database module
#play.modules.enabled += "play.api.db.DBModule"

slick.dbs.default.profile="slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver="com.mysql.cj.jdbc.Driver"

slick.dbs.default.db.url="jdbc:mysql://azuremysql8823.mysql.database.azure.com:3306/naresh"

slick.dbs.default.db.user="mysqladmin"
slick.dbs.default.db.password="Password@12345"
play.evolutions.db.default.autoApply=true



play.filters.cors {
  pathPrefixes = ["/api"]              # Match your API routes
  allowedOrigins = ["*"]               # Or restrict to specific domains in production
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Origin", "Content-Type", "X-Auth-Token"]
  preflightMaxAge = 3 days
}

play.http.filters = "filters.Filters"

jwt {
  secret = "YThgvvjjhvYDYCHvjhbvjhbjhjVGVJHvjhkhbkbkhvIUGIGK"
  expiryMillis = 3600000
}
