paths {

#broadcast
  transactions = "broadcast/transactions"
  exchangeRates = "broadcast/exchange_rates"
  output = "broadcast/output/currency_counts"

#caching
  sales = "caching/sales_data"
  customerOutput = "caching/output/customer_spending"
  productOutput = "caching/output/product_sales"
  customerOutputCached = "caching/output/customer_spending_cached"
  productOutputCached = "caching/output/product_sales_cached"

 # Transaction accumulator project
  accum_transactions = "accumulator/transactions"
  accum_output = "accumulator/output"


  logCoalesce_input = "logCoalesce/input"
  logCoalesce_outputBefore = "logCoalesce/output/before"
  logCoalesce_outputAfter = "logCoalesce/output/after"



}
